@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePropertyList
Class UniqueBuyerList
Class UniqueMatchList
Class Property
Class Buyer
Class Match
Class Price
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePropertyList
AddressBook *--> "1 sorted" UniquePropertyList
UniquePropertyList -down---> "~* all" Property
Property *--> Name
Property *--> Person
Property *--> Address
Property *--> Price
Property *--> "*" Tag

AddressBook *--> "1" UniqueBuyerList
AddressBook *--> "1 sorted" UniqueBuyerList
UniqueBuyerList -[hidden]left-> UniquePropertyList
UniqueBuyerList --> "~* all" Buyer
Buyer --|> Person
Buyer *--> Price
Buyer *--> "*" Tag


AddressBook *--> "1" UniqueMatchList
UniqueMatchList -[hidden]left-> UniqueBuyerList
UniqueMatchList -down---> "*" Match
Match -right--> "1" Buyer
Match -right--> "     1" Property
Buyer -[hidden]right--> "1" Property

Property -[hidden]right-> Buyer

Person *--> Name
Person *--> Email
Person *--> Phone

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Property
ModelManager -->"~* filtered" Buyer
@enduml
