@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
together {
    Class HelpWindow
    Class StatWindow
    Class ResultDisplay
    Class PropertyListPanel
    Class BuyerListPanel
    Class MatchListPanel
    Class StatusBarFooter
    Class CommandBox
}
Class PropertyCard
Class BuyerCard
Class MatchCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PropertyListPanel
MainWindow *-down-> "1" BuyerListPanel
MainWindow *-down-> "1" MatchListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" StatWindow

PropertyListPanel --down-> "*" PropertyCard
BuyerListPanel --down-> "*" BuyerCard
MatchListPanel --down-> "*" MatchCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PropertyListPanel --|> UiPart
PropertyCard --|> UiPart
BuyerListPanel --|> UiPart
BuyerCard --|> UiPart
MatchListPanel --|> UiPart
MatchCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
StatWindow --|> UiPart

PropertyCard ..down.> Model
BuyerCard ..down.> Model
MatchCard ..down.> Model
UiManager -right-> Logic
MainWindow -left-> Logic

MatchListPanel -[hidden]left- BuyerListPanel
BuyerListPanel -[hidden]left- PropertyListPanel
PropertyListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
